title: Berke Akkaya
logo: /profile.png
description: >- 
  Researcher in Recommender Systems | NLP & Machine Learning Enthusiast  
  Ph.D. Candidate in Quantitative Methods, Istanbul University

github_username: b-erke
linkedin_username: berke-akkaya
email: berkeakkaya@istanbul.edu.tr

theme: jekyll-theme-minimal
