title: Berke Akkaya
#logo: /profile.png
description: >- 
  Researcher in Machine Learning |
  Ph.D. Candidate in Quantitative Methods, Istanbul University

github_username: b-erke
linkedin_username: berke-akkaya
email: berkeakkaya@istanbul.edu.tr

theme: jekyll-theme-minimal
